### ISSUE TITLE
Long titles cause misalignments

### ISSUE THREAD

**Issue by davcri** [GDquest/godot-3-presentation#21]
How to reproduce the issue:

- Open `Header.tscn`
- Edit `Title.text` to be a long string (it should contain at least 40 characters)
- Revert `Title.text` to a short string (< 40 chars)

Now you can see that the label centers its content, but the rectangle dimensions are changed: this is the cause of the misalignment.

![screenshot from 2018-04-26 22-44-32](https://user-images.githubusercontent.com/6860637/39333765-fc7c4dc6-49a3-11e8-9a77-fd59476bcb8d.png)
![screenshot from 2018-04-26 22-45-03](https://user-images.githubusercontent.com/6860637/39333766-fc97c29a-49a3-11e8-88b5-4040d058ee7e.png)
![screenshot from 2018-04-26 22-45-14](https://user-images.githubusercontent.com/6860637/39333767-fcb2a952-49a3-11e8-8b1a-4fd5ae9cfaa1.png)

---

I noticed this issue while taking a look at the Italian translation.

Enabling autowrapping could help, but it's not a perfect solution.
Probably it's better to warn translators to pay attention when writing titles.

**Comment by NathanLovato** [comment]
That's what #20 is for: titles should be short but for languages where words are longer than english we should also be able to override some properties like font sizes. Adding clipping to fix the container sizing issue
