### ISSUE TITLE
Proposal for *.json

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/godot-3-presentation#28]
Hey, I'm making the port of the data from `.gd` to `.json` already, I think it will be a good first step.

One of the things that I find would be useful is to set the `picture` parameter always be an array of pictures, instead of a single one.

This way we will be able to use some dynamic usage of `GridContainer` in order to display said pictures.

**Comment by NathanLovato** [comment]
If you're doing it as a contributor it's fine, but that's not part of this freelance job. I hope you're not doing it manually! Converting the data to JSON should take little time. I'm booked today but I can do it tomorrow if you want. Anyway, you can work with a .gd file in the meantime, it's just as fast to write. Then I'll convert all presentations with a script.
