### ISSUE TITLE
Proposal for new presentation data structure

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/godot-3-presentation#29]
In the current implementation it presumes that every presentation shall have:

- Intro
- Health
- Concepts
- Features
- Learning
- Questions

Which are dictionaries with the given content, I'm thinking about instead allowing for the `Presentation` to pick up a folder (through a `String` exported to the editor) and from there automatically pick every `.json` file, which will correspond each to a single slide.

This will probably demand a way to create an order for the slides, as it is not reliable to programmatically do it from the `Presentation` itself.

To achieve that I think we can add

- Previous
- Next

Properties as addition to  #28 this potentially eases #11 as well

**Comment by henriiquecampos** [comment]
Also, this will make the presentation itself more modular, allowing for any sort of change in the slides structures with easy implementation.

**Comment by NathanLovato** [comment]
Let's use 1 json file for the entire presentation - this way the order is the order of the slide objects in the JSON file. And when loading the json, all we'll have to do is to parse as a list of slide node instances, or as an array of SlideData, something like that.

**Comment by NathanLovato** [comment]
Fixed with 75580ab23994214b83562c8b2f7ccbb188b47945
