### ISSUE TITLE
Make videos available through Git

### ISSUE THREAD

**Issue by fleskesvor** [GDquest/godot-3-presentation#8]
As far as I understand, videos have to be downloaded through a separate zip to reduce the download size. I understand the rationale, however, I think there are better ways to achieve this:

- [Git LFS](https://git-lfs.github.com/) - a user which doesn't have Git LFS will only get the pointer files, so it's still possible to download the repo without the video assets
- A seperate video repository which can be cloned into `godot-3-presentation/godot-3-presentation/slides/videos/` and that directory is added to the `.gitignore` of this project.

These approaches both achieve pretty much the same thing, and the second can also be combined with LFS, which gives some options for specifying which files to download if relevant.

**Comment by NathanLovato** [comment]
Git LFS is a good idea. I'll add that later today (the upload time, from home, is going to be a bit long)

**Comment by fleskesvor** [comment]
Thanks for adding the videos. 🙂
